#!/bin/bash

set -x
set -e

apitrace=""
while getopts 'a:' opt ; do
    case $opt in
        a)
            apitrace=--print-api-trace
            shift;;
        \?)
            exit 1
            ;;
    esac
done

LOG_FILE=$(mktemp)
LOCK_FILE=/tmp/gnvprof_lock

/usr/local/cuda/bin/nvprof \
    --csv \
    --aggregate-mode off \
    --print-gpu-trace \
    $(echo "$apitrace") \
    --normalized-time-unit us \
    --log-file "$LOG_FILE" \
    -- "$@" > /dev/null

PARSED_LOG=$(mktemp)
cat "$LOG_FILE" | sed '1,/Profiling result:/d' | head -n -5 > "$PARSED_LOG"
# Support concurrent disto processes + nvprof, don't forget to:
# cat /tmp/disto*out | sed -e "s/\n\]\n\[/,\n/g" > /tmp/prof
lockfile "$LOCK_FILE"
"$(dirname "$0")/gnvprof.py" "$PARSED_LOG"
rm -f "$LOCK_FILE"
